from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List, Optional

from backend.app.db import get_db
from backend.data.db_schema import ActionLog, LeakAlert, RevenueLog, Zone, NRWSnapshot
from backend.app.models import ActionCreate, ActionResponse
from backend.app.engines.revenue import calculate_revenue_recovered

router = APIRouter(prefix="/actions", tags=["Actions & Approval Workflow"])

@router.post("/create", response_model=ActionResponse)
def create_action(payload: ActionCreate, db: Session = Depends(get_db)):
    """Creates a new action recommendation (typically generated by AI Copilot)."""
    zone = db.query(Zone).filter(Zone.id == payload.zone_id).first()
    if not zone:
        raise HTTPException(status_code=404, detail=f"Zone '{payload.zone_id}' not found.")

    action = ActionLog(
        zone_id=payload.zone_id,
        alert_id=payload.alert_id,
        action_type=payload.action_type,
        urgency=payload.urgency,
        estimated_cost=payload.estimated_cost,
        estimated_payback_days=payload.estimated_payback_days,
        officer_notes=payload.officer_notes,
        status="PENDING"
    )
    db.add(action)
    db.commit()
    db.refresh(action)
    return action

@router.get("/", response_model=List[ActionResponse])
def list_actions(
    zone_id: Optional[str] = Query(None, description="Filter by zone ID"),
    status: Optional[str] = Query(None, description="Filter by status: PENDING, APPROVED, REJECTED, RESOLVED"),
    db: Session = Depends(get_db)
):
    """Lists actions for municipal water officers."""
    query = db.query(ActionLog)
    if zone_id:
        query = query.filter(ActionLog.zone_id == zone_id)
    if status:
        query = query.filter(ActionLog.status == status.upper())
    return query.order_by(ActionLog.created_at.desc()).all()

@router.post("/approve/{action_id}", response_model=ActionResponse)
def approve_action(action_id: int, officer_notes: Optional[str] = None, db: Session = Depends(get_db)):
    """Officer approves proposed repair action."""
    action = db.query(ActionLog).filter(ActionLog.id == action_id).first()
    if not action:
        raise HTTPException(status_code=404, detail=f"Action ID {action_id} not found.")

    action.status = "APPROVED"
    if officer_notes:
        action.officer_notes = (action.officer_notes or "") + f" | Approved: {officer_notes}"
    db.commit()
    db.refresh(action)
    return action

@router.post("/reject/{action_id}", response_model=ActionResponse)
def reject_action(action_id: int, reason: str, db: Session = Depends(get_db)):
    """Officer rejects proposed repair action."""
    action = db.query(ActionLog).filter(ActionLog.id == action_id).first()
    if not action:
        raise HTTPException(status_code=404, detail=f"Action ID {action_id} not found.")

    action.status = "REJECTED"
    action.officer_notes = (action.officer_notes or "") + f" | Rejected: {reason}"
    db.commit()
    db.refresh(action)
    return action

@router.post("/resolve/{action_id}", response_model=ActionResponse)
def resolve_action_and_auto_recover(action_id: int, db: Session = Depends(get_db)):
    """
    AUTO-RECOVERY MILESTONE:
    When an approved action is completed, this marks action RESOLVED,
    resolves the associated alert, auto-calculates revenue recovered,
    writes to `revenue_log`, and records a new entry in `nrw_snapshots`.
    """
    action = db.query(ActionLog).filter(ActionLog.id == action_id).first()
    if not action:
        raise HTTPException(status_code=404, detail=f"Action ID {action_id} not found.")

    zone = db.query(Zone).filter(Zone.id == action.zone_id).first()
    tariff = zone.tariff_rate if zone else 0.005

    action.status = "RESOLVED"
    action.resolved_at = datetime.utcnow()

    recovered_litres = 50000.0
    if action.alert_id:
        alert = db.query(LeakAlert).filter(LeakAlert.id == action.alert_id).first()
        if alert:
            alert.status = "RESOLVED"
            recovered_litres = alert.estimated_loss_litres

    recovered_rupees = calculate_revenue_recovered(recovered_litres, tariff)
    revenue_entry = RevenueLog(
        zone_id=action.zone_id,
        alert_id=action.alert_id,
        litres_recovered=recovered_litres,
        tariff_rate=tariff,
        revenue_recovered=recovered_rupees,
        notes=f"Auto-generated on resolution of Action #{action.id} ({action.action_type})"
    )
    db.add(revenue_entry)

    snapshot = NRWSnapshot(
        zone_id=action.zone_id,
        nrw_percentage=18.5,  # Reduced from 55% post-repair
        inflow_litres=100000.0,
        billed_litres=81500.0,
        loss_litres=18500.0
    )
    db.add(snapshot)

    db.commit()
    db.refresh(action)
    return action

if __name__ == "__main__":
    print("Actions router created successfully!")